spring.application.name=QuantityMeasurementApp
server.port=8081

# Repository Type Configuration either "cache" or "database"
repository.type=database

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Database (Development)
spring.datasource.url=jdbc:mysql://172.31.33.159:3306/quantitydb
spring.datasource.username=quantityadmin
spring.datasource.password=Quantity@123

spring.jpa.hibernate.ddl-auto=update

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Logging Configuration
logging.level.root=WARN
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=app.login

# Custom log pattern for console output to include timestamp, logger name, and message
# The pattern includes:
# %d{yyyy-MM-dd HH:mm:ss} - Timestamp in the format of year-month-day hour:minute:second
# %logger{36} - Logger name truncated to 36 characters
# %line - Line number where the log statement was issued
# %msg%n - The log message followed by a new line
# console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{5}:%line] %msg%n"
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{5}:%line - %msg%n

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
